# Generated by Django 5.2.6 on 2026-02-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt_ai', '0003_remove_doubthistory_session_doubtconversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubthistory',
            name='conversation',
        ),
        migrations.AlterModelOptions(
            name='doubthistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='DoubtConversation',
        ),
    ]
