# Generated by Django 5.2.6 on 2026-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], default='CSE', max_length=10),
        ),
    ]
