# Generated by Django 5.2.6 on 2026-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
