# Generated by Django 5.2.6 on 2026-02-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
    ]
