# Generated by Django 5.2.6 on 2026-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='weekly_notes',
            field=models.TextField(blank=True, help_text='AI generated notes for the week', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='breakdown',
            field=models.JSONField(blank=True, help_text='Per question time and correctness', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time taken in seconds'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Step-by-step analysis', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='trick',
            field=models.TextField(blank=True, help_text='Trick to solve in less time', null=True),
        ),
    ]
