from django.db import models
from django.conf import settings

class StudyGroup(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    subject = models.CharField(max_length=100)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='study_groups')
    created_at = models.DateTimeField(auto_now_add=True)
    
    # AI Matching Preferences
    preferred_learning_style = models.CharField(max_length=20, choices=[('Any', 'Any'), ('Visual', 'Visual'), ('Auditory', 'Auditory')])
    difficulty_level = models.CharField(max_length=20, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')])

    # AI Admin Scheduling
    ai_schedule = models.JSONField(null=True, blank=True, help_text="Day-to-day learning schedule and notes generated by AI")
    schedule_last_updated = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name

class UserGroupProgress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)
    completed_days = models.JSONField(default=list, help_text="List of completed day numbers")
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'group')

    def is_completed(self, day_number):
        return day_number in self.completed_days

    def can_unlock(self, day_number):
        if day_number == 1:
            return True
        return (day_number - 1) in self.completed_days
