# Generated by Django 5.2.6 on 2026-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_studygroup_subject_delete_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='ai_schedule',
            field=models.JSONField(blank=True, help_text='Day-to-day learning schedule and notes generated by AI', null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='schedule_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
