# Generated by Django 5.2.6 on 2026-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_studygroup_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='current_week',
            field=models.IntegerField(default=1),
        ),
    ]
